### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vinimdocarmo** [gergelyke/blog#7]
Hi @gergelyke, I've just read your last post and this was the first time I visit your blog page. I have this willing of starting to write a blog, mainly to write about my adventures learning Go.

I was wandering whether or not I can use your blog project as a starting point for my own blog page. Since this project has no license I will ask: may I fork, use and modify this project to start my own? This permission would not include the usage of your posts of course.

Furthermore, It'd be useful to add a license to your projeto.

Last but not least, great posts of your own! 👏

**Comment by gergelyke** [comment]
Hi @vinimdocarmo,

thanks for the kind words! I'd recommend checking out https://hexo.io/ if you'd like to build something similar :)

**Comment by vinimdocarmo** [comment]
Thank you, @gergelyke!
